name: Build and deploy Node.js app to Azure Web App - CulinaryMasteryApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        env:
          NODE_OPTIONS: --max-old-space-size=12288
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "node_modules/*" "*.log" "coverage/*" ".git/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Wait for App Service to stabilize
        run: sleep 30

      - name: Verify PORT environment variable
        run: echo "PORT is set to $PORT"
        env:
          PORT: 8080

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        env:
          NODE_OPTIONS: --max-old-space-size=12288
        uses: azure/webapps-deploy@v3
        with:
          app-name: "CulinaryMasteryApp"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B83936E41098423E9C5994A326CFE7D0 }}
